### ISSUE TITLE
Update for image_processing.doods_XXXX fails

### ISSUE THREAD

**Issue by drk-geek** [snowzach/hassdoods#6]
Hi,
I installed this as add-on in my HA instance using add-on store and it starts working. After one it stop working with following error

"_Update for image_processing.doods_xxxx fails_"

Below is the full log from HA logs

_Logger: homeassistant.helpers.entity
Source: helpers/template.py:378
First occurred: 5:08:59 AM (81 occurrences)
Last logged: 5:22:18 AM

Update for image_processing.doods_front_left fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 376, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1327, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1351, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1343, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
jinja2.exceptions.UndefinedError: 'camera' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 138, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 118, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/doods/image_processing.py", line 380, in process_image
    path_template.render(camera_entity=self._camera_entity)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 346, in render
    return run_callback_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 57, in run_callback
    future.set_result(callback(*args))
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 378, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'camera' is undefined_

Any fix?

**Comment by snowzach** [comment]
That honestly looks like a home assistant error. I haven't changed anything in this repo since it started.

**Comment by drk-geek** [comment]
any recommendation to fix this error ?

**Comment by snowzach** [comment]
This is real old. Hopefully you figured it out. I didn't really have any suggestions.
